[package]
name = "flux-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
base64.workspace = true
html5ever.workspace = true
image.workspace = true
markup5ever_rcdom.workspace = true
resvg.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ureq.workspace = true
url.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tiny-skia.workspace = true
usvg.workspace = true

[dev-dependencies]
tempfile.workspace = true
