import AppKit
import SwiftUI

enum PopoverLayout { static let articleWidth: CGFloat = 620; static let sidebarWidth: CGFloat = 240; static let height: CGFloat = 620; static let animation: TimeInterval = 0.2 }
private enum ArticleScrollSpace { static let name = "FluxBar.ArticleScroll" }
private struct ArticleFrameKey: PreferenceKey { static var defaultValue: [Int64: CGRect] = [:]; static func reduce(value: inout [Int64: CGRect], nextValue: () -> [Int64: CGRect]) { value.merge(nextValue(), uniquingKeysWith: { _, new in new }) } }

struct PopoverContentView: View {
    @ObservedObject var store: BrowserStore
    let layoutChanged: (Bool) -> Void
    let dismiss: () -> Void
    @State private var sidebarVisible = false
    var body: some View { HStack(spacing: 0) { if sidebarVisible { NavigationSidebar(store: store).frame(width: PopoverLayout.sidebarWidth).overlay(alignment: .trailing) { Divider() }.transition(.move(edge: .leading).combined(with: .opacity)) }; ArticlePane(store: store, sidebarVisible: $sidebarVisible, layoutChanged: layoutChanged, dismiss: dismiss).frame(width: PopoverLayout.articleWidth) }.frame(width: PopoverLayout.articleWidth + (sidebarVisible ? PopoverLayout.sidebarWidth : 0), height: PopoverLayout.height).sheet(isPresented: $store.settingsVisible) { SettingsView(store: store) } }
}

private struct ArticlePane: View {
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @ObservedObject var store: BrowserStore
    @Binding var sidebarVisible: Bool
    let layoutChanged: (Bool) -> Void
    let dismiss: () -> Void
    @State private var tracker = ScrolloverExposureTracker()
    @State private var frames: [Int64: CGRect] = [:]
    @State private var viewport = CGRect.zero
    @State private var selectedID: Int64?
    @State private var scrollPhase = ScrollPhase.idle
    @State private var suppressUntil: TimeInterval = 0
    private let timer = Timer.publish(every: 0.2, on: .main, in: .common).autoconnect()
    var body: some View { VStack(spacing: 0) { header; Divider(); content }.background(.regularMaterial).overlay(alignment: .bottom) { if store.newDataAvailable { updateBanner.padding(.bottom, 12) } else if store.scrolloverUndoVisible { undoBanner.padding(.bottom, 12) } }.onReceive(timer) { _ in observe() }.onChange(of: store.articles.map(\.id)) { _, _ in tracker.reset(); selectedID = nil }.onChange(of: store.popoverVisible) { _, _ in tracker.reset() } }
    private var header: some View { HStack(spacing: 8) { Button { if reduceMotion { sidebarVisible.toggle() } else { withAnimation(.easeInOut(duration: PopoverLayout.animation)) { sidebarVisible.toggle() } }; layoutChanged(sidebarVisible) } label: { Image(systemName: "sidebar.left") }.buttonStyle(.borderless); Text(title).font(.headline).lineLimit(1); Text("\(store.selectionTotal)").font(.caption.monospacedDigit()).foregroundStyle(.secondary); Spacer(); Button { store.sync() } label: { store.isLoading ? AnyView(ProgressView().controlSize(.small)) : AnyView(Image(systemName: "arrow.clockwise")) }.buttonStyle(.borderless).disabled(store.isLoading); Menu { Button("Unread only") { store.setUnreadOnly(true) }; Button("All articles") { store.setUnreadOnly(false) }; Divider(); Button("Oldest first") { store.setNewestFirst(false) }; Button("Newest first") { store.setNewestFirst(true) }; Divider(); Button("Settings...") { store.settingsVisible = true }; Button("Quit FluxBar") { NSApplication.shared.terminate(nil) } } label: { Image(systemName: "gearshape") }.menuStyle(.borderlessButton).menuIndicator(.hidden) }.padding(.horizontal, 12).padding(.vertical, 9) }
    @ViewBuilder private var content: some View { if let error = store.errorMessage, store.articles.isEmpty { ContentUnavailableView("Refresh failed", systemImage: "exclamationmark.triangle", description: Text(error)) } else if store.isLoading && store.articles.isEmpty { ProgressView().frame(maxWidth: .infinity, maxHeight: .infinity) } else if store.articles.isEmpty { ContentUnavailableView("No articles", systemImage: "tray") } else { GeometryReader { geometry in ScrollViewReader { proxy in ScrollView { LazyVStack(spacing: 0) { ForEach(store.articles, id: \.id) { article in ArticleRow(article: article, selected: selectedID == article.id, store: store, select: { selectedID = article.id }).id(article.id).background { GeometryReader { Color.clear.preference(key: ArticleFrameKey.self, value: [article.id: $0.frame(in: .named(ArticleScrollSpace.name))]) } }; Divider().padding(.leading, 144) } } }.coordinateSpace(name: ArticleScrollSpace.name).onScrollGeometryChange(for: CGFloat.self) { $0.contentOffset.y } action: { old, new in scrollChanged(new - old) }.onScrollPhaseChange { _, phase in scrollPhase = phase; if !userScrolling { tracker.rebase(frames: frames, unread: unreadIDs) } }.background { KeyboardCommandObserver { command in handle(command, proxy: proxy) } }.onAppear { viewport = CGRect(origin: .zero, size: geometry.size); observe() }.onChange(of: geometry.size) { _, size in viewport = CGRect(origin: .zero, size: size); tracker.reset() }.onPreferenceChange(ArticleFrameKey.self) { frames = $0; if !userScrolling { tracker.rebase(frames: frames, unread: unreadIDs) }; observe() } } } } }
    private var updateBanner: some View { HStack(spacing: 10) { Text("New articles available"); Button("Refresh") { store.applyNewData() }.buttonStyle(.borderless) }.padding(.horizontal, 12).padding(.vertical, 8).background(.regularMaterial, in: Capsule()).shadow(radius: 4, y: 2) }
    private var undoBanner: some View { HStack(spacing: 10) { Text("\(store.lastScrolloverBatch.count) articles marked as read"); Button("Undo") { store.undoScrollover() }.buttonStyle(.borderless) }.padding(.horizontal, 12).padding(.vertical, 8).background(.regularMaterial, in: Capsule()).shadow(radius: 4, y: 2) }
    private var title: String { switch store.scope { case .all: "All News"; case .starred: "Starred"; case let .category(id): store.catalog.categories.first(where: { $0.id == id })?.title ?? "Category"; case let .feed(id): store.catalog.feeds.first(where: { $0.id == id })?.title ?? "Feed" } }
    private var unreadIDs: Set<Int64> { Set(store.articles.filter { !$0.isRead }.map(\.id)) }
    private var userScrolling: Bool { scrollPhase != .idle && scrollPhase != .animating }
    private func observe() { guard store.popoverVisible, store.markReadOnScrolloverEnabled, ProcessInfo.processInfo.systemUptime >= suppressUntil, !viewport.isEmpty else { return }; tracker.observe(frames: frames, viewport: viewport, unread: unreadIDs, now: Date.timeIntervalSinceReferenceDate) }
    private func scrollChanged(_ delta: CGFloat) { guard userScrolling else { tracker.rebase(frames: frames, unread: unreadIDs); return }; store.noteMeaningfulInteraction(); guard store.markReadOnScrolloverEnabled, ProcessInfo.processInfo.systemUptime >= suppressUntil else { return }; let ids = tracker.process(frames: frames, viewport: viewport, unread: unreadIDs, now: Date.timeIntervalSinceReferenceDate, offsetDelta: delta, userInitiated: true); if !ids.isEmpty { store.flushScrollover(ids) } }
    private func handle(_ command: ArticleKeyboardCommand, proxy: ScrollViewProxy) { switch command { case .moveUp: move(-1, proxy); case .moveDown: move(1, proxy); case .open: if let article = selected { store.open(article) }; case .toggleRead: if let article = selected { store.setRead(article, !article.isRead) }; case .toggleStarred: if let article = selected { store.setStarred(article, !article.isStarred) }; case .refresh: store.sync(); case .dismiss: dismiss() } }
    private var selected: ArticleSummary? { selectedID.flatMap { id in store.articles.first { $0.id == id } } }
    private func move(_ delta: Int, _ proxy: ScrollViewProxy) { guard !store.articles.isEmpty else { return }; let current = selectedID.flatMap { id in store.articles.firstIndex { $0.id == id } }; let index = min(max(0, (current ?? (delta < 0 ? store.articles.count : -1)) + delta), store.articles.count - 1); selectedID = store.articles[index].id; suppressUntil = ProcessInfo.processInfo.systemUptime + 0.4; tracker.reset(); proxy.scrollTo(store.articles[index].id, anchor: .center) }
}

private struct NavigationSidebar: View { @ObservedObject var store: BrowserStore; var body: some View { List { Section { Button("All News") { store.select(.all) }.badge(Int(store.unreadTotal)); Button("Starred") { store.select(.starred) }.badge(Int(store.starredTotal)) }; Section("Feeds") { ForEach(store.catalog.categories, id: \.id) { category in DisclosureGroup(category.title) { ForEach(store.catalog.feeds.filter { $0.categoryId == category.id }, id: \.id) { feed in Button(feed.title) { store.select(.feed(feed.id)) }.badge(Int(store.sidebarCounts[feed.id] ?? 0)) } }.onTapGesture { store.select(.category(category.id)) }.badge(Int(store.sidebarCounts[category.id] ?? 0)) } } }.listStyle(.sidebar).scrollContentBackground(.hidden).background(.regularMaterial) } }

private struct ArticleRow: View { let article: ArticleSummary; let selected: Bool; @ObservedObject var store: BrowserStore; let select: () -> Void; @State private var hovered = false; var body: some View { HStack(alignment: .top, spacing: 12) { Button { select(); store.open(article) } label: { HStack(alignment: .top, spacing: 12) { Image(systemName: "photo").frame(width: 120, height: 84).background(.quaternary).clipShape(RoundedRectangle(cornerRadius: 6)); VStack(alignment: .leading, spacing: 5) { HStack(spacing: 5) { Text(article.feedTitle); Text("·"); Text(article.publishedAt); if !article.commentsUrl.isEmpty { Image(systemName: "bubble.left") }; if article.isStarred { Image(systemName: "star.fill").foregroundStyle(.yellow) } }.font(.caption).foregroundStyle(article.isRead ? .tertiary : .secondary); Text(article.title).fontWeight(article.isRead ? .regular : .semibold).foregroundStyle(article.isRead ? .secondary : .primary).lineLimit(3) } }.contentShape(Rectangle()) }.buttonStyle(.plain); actions.opacity(hovered ? 1 : 0).allowsHitTesting(hovered) }.padding(.horizontal, 12).padding(.vertical, 10).contentShape(Rectangle()).background(selected ? Color.accentColor.opacity(0.16) : hovered ? Color.primary.opacity(0.055) : .clear).onHover { hovered = $0 }.onTapGesture { select() }.contextMenu { menu } }
    private var actions: some View { VStack(spacing: 8) { Button { store.setRead(article, !article.isRead) } label: { Image(systemName: article.isRead ? "circle.fill" : "checkmark.circle") }.buttonStyle(.borderless); Button { store.setStarred(article, !article.isStarred) } label: { Image(systemName: article.isStarred ? "star.fill" : "star") }.buttonStyle(.borderless); Menu { menu } label: { Image(systemName: "ellipsis") }.menuStyle(.borderlessButton).menuIndicator(.hidden) } }
    @ViewBuilder private var menu: some View { Button("Open in Browser") { store.open(article) }; Button(article.isRead ? "Mark Unread" : "Mark Read") { store.setRead(article, !article.isRead) }; Button(article.isStarred ? "Unstar" : "Star") { store.setStarred(article, !article.isStarred) }; Divider(); Button("Copy Link") { store.copyLink(article) }; Button("Share...") { store.share(article) }; Button("Show Feed") { store.select(.feed(article.feedId)) }; if !article.commentsUrl.isEmpty { Button("Open Comments") { store.openComments(article) } } }
}

private struct SettingsView: View { @ObservedObject var store: BrowserStore; @State private var server = ""; @State private var key = ""; @State private var scrollover = true; var body: some View { Form { TextField("Miniflux server", text: $server); SecureField("API key", text: $key); Toggle("Mark articles as read when scrolling past", isOn: $scrollover); Button("Save") { store.setScrolloverEnabled(scrollover); store.configure(server: server, apiKey: key); store.settingsVisible = false } }.padding().frame(width: 420).onAppear { server = UserDefaults.standard.string(forKey: "Flux.server") ?? ""; scrollover = store.markReadOnScrolloverEnabled } } }
